services:
  # 1. Redis
  - type: redis
    name: currency-redis
    plan: free

  # 2. Backend
  - type: web
    name: currency-api
    runtime: docker
    # rootDir tells Render to "cd" into this folder before doing anything
    rootDir: backend
    dockerfilePath: Dockerfile 
    dockerContext: .
    plan: free
    envVars:
      - key: REDIS_HOST
        value: currency-redis
      - key: REDIS_PORT
        value: "6379"
      - key: OPENEXCHANGERATES_API_KEY
        sync: false

  # 3. Frontend
  - type: web
    name: currency-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    dockerBuildArgs:
      - arg: REACT_APP_API_URL
        fromService:
          type: web
          name: currency-api
          property: host
    envVars:
      - key: PORT
        value: "3000"
